### ISSUE TITLE
Any option to obtain Sub-Regions?

### ISSUE THREAD

**Issue by matbmeijer** [holidayapi/node-holidayapi#4]
Hi Josh,

First of all, thank you very much for this great tool. I enhoy the simplicity for the enduser of the API - that's why I am trying to build an API wrapper for the statistical programming language R, and I was wondering if there is any option to not only obtain a list of the countries, but also their subregions. I went through the documentation, but I could not find anything. I believe it would be a great addition to the "https://holidayapi.com/v1/holidays" endpoint.

Additionally, ¿which subregions are you considering? ¿Are they FIPS codes or ISO 3166-2 codes?

Last but not least, this might be a "noob" question - and it might be that the parameter acts as boolean (if passed = TRUE, else FALSE), but I´ll ask anyway:
The output if I use pretty=TRUE / pretty=FALSE / pretty=1 / pretty=0 is always the same --> pretty. It only acts as FALSE if I do not use the parameter. Is this the desired behaviour?

Thank you in advance!

**Comment by joshtronic** [comment]
Initially I had implemented the subdivisions to be queries independently of the country, so for a US state, you'd pass in US-TX (or whatever the code is for the state you want).

After a ton of conversations with users, I realized that I kinda effed up with that one, and we recently added a "subdivisions" flag that allows for the querying of the country, AND includes the subdivision specific holidays. It's not entirely perfect, but it's a good gap fill until version 2 of the API data structure is released (no ETA on that at the moment).

Currently the subdivisions are using the ISO-3166 codes.

Regarding the flag, being present vs. being truly boolean, totally not a noob thing (actually more of a noob implementation on my end). Not sure why I went that route, but yeah, if the boolean flag is present, it's considered true regardless of value.

Going to put that on my punch list to fix since it's confusing behavior, especially with it being defined as boolean.

Many apologies on the late reply. Also, thanks for the praise and assuming you don't mind, I'm going to get your R wrapper added to our docs page.

Cheers!
